//
// Generated file, do not edit! Created by nedtool 4.6 from R_PDU.msg.
//

#ifndef _R_PDU_M_H_
#define _R_PDU_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
    #include<map>
    #include<utility>
    typedef std::map<int,std::pair<int,int>> MapType;
// }}

/**
 * Class generated from <tt>R_PDU.msg:25</tt> by nedtool.
 * <pre>
 * packet R_PDU
 * {
 *     int seq;
 *     MapType rtable;
 * 
 * }
 * </pre>
 */
class R_PDU : public ::cPacket
{
  protected:
    int seq_var;
    MapType rtable_var;

  private:
    void copy(const R_PDU& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const R_PDU&);

  public:
    R_PDU(const char *name=NULL, int kind=0);
    R_PDU(const R_PDU& other);
    virtual ~R_PDU();
    R_PDU& operator=(const R_PDU& other);
    virtual R_PDU *dup() const {return new R_PDU(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getSeq() const;
    virtual void setSeq(int seq);
    virtual MapType& getRtable();
    virtual const MapType& getRtable() const {return const_cast<R_PDU*>(this)->getRtable();}
    virtual void setRtable(const MapType& rtable);
};

inline void doPacking(cCommBuffer *b, R_PDU& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, R_PDU& obj) {obj.parsimUnpack(b);}


#endif // ifndef _R_PDU_M_H_

